MODEL:
  META_ARCHITECTURE: 'HAA_BASELINE'

  OPEN_LAYERS: ""

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: 50
    LAST_STRIDE: 1
    PRETRAIN: True

  HEADS:
    NAME: "BNneckHead"
    CLS_LAYER: "linear"
    POOL_LAYER: "gempool"
    NUM_CLASSES: 688

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")

    CE:
      EPSILON: 0.1
      SCALE: 1.0     

    TRI:
      MARGIN: 1.2
      HARD_MINING: True
      USE_COSINE_DIST: False
      SCALE: 1.0

DATASETS:
  NAMES: ("PRCV",)
  TESTS: ("PRCV",)
  DATASETS_ROOT: "/home/yhl/data/"
  STN_ROOT: "/home/yhl/reid/HAA/stn_blackreid.pth"

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]
  DO_PAD: True


DATALOADER:
  PK_SAMPLER: True
  NUM_INSTANCE: 4#4
  NUM_WORKERS: 16#16

SOLVER:
  OPT: "Adam"
  MAX_ITER: 15000
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [3520, 6160]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 880

  LOG_PERIOD: 880
  CHECKPOINT_PERIOD: 880

TEST:
  EVAL_PERIOD: 1000
  IMS_PER_BATCH: 512

CUDNN_BENCHMARK: True

OUTPUT_DIR: "logs/black_reid"
