_BASE_: "Base-HAA.yml"

MODEL:
  META_ARCHITECTURE: 'HAA_MGN'

  BACKBONE:
    PRETRAIN: true
    PRETRAIN_PATH: /home/yhl/.torch/models/resnet50_ibn_a.pth.tar
    WITH_IBN: true

  HEADS:
    NUM_CLASSES: 1295

SOLVER:
  OPT: "Adam"
  MAX_ITER: 9000
  
  STEPS: [3520, 6160]
  
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 880

  LOG_PERIOD: 100
  CHECKPOINT_PERIOD: 880
  
TEST:
  EVAL_PERIOD: 10000
  IMS_PER_BATCH: 512

OUTPUT_DIR: "logs/HAA_mgn_blackreid-total"